### PR TITLE
feat: add useRedux method

### PR DESCRIPTION
**Pull request by FBerthelot**
After use of this library, @swiip and I found there is possibility to improve redux with hook.

The main goal of this PR is to add `useRedux` method, a shortcut that combine `useDispatch`, `useMappedState` and `useCallback` with memo.

### CODE REVIEW

**Comment by ianobermiller** [comment]
This has the same downsides of #31, but worse in fact since you are reusing the memo array for both callbacks. I'm reaching out to the React team about the `WithDeps` convention or how they think about custom hooks taking dependencies.

> there is possibility to improve redux with hook

In the spirit of keeping this library small, I don't see a whole lot of value in pushing all of these together. I get that this can relieve some typing, but I prefer the fact that `useMappedState` and `useDispatch` are separate, since they aren't always used together. Of course they still exist, but I think adding a dependency param to `useMappedState` and potentially adopting `useMappedDispatch` will clean things up enough that an all over `useRedux` isn't required. It is also very easy to implement in user-code -- the heavy lifting is still taken care of by `redux-react-hook`.

**Comment by Swiip** [comment]
I understand the downsides and the willing of minimalism, really. I'm not sure that the API we propose is perfect...

Yet, don't you agree that using 4 hooks, 2 `useCallback`s, `useMappedState`, `useDispatch` for a really simple example on the main readme is really complex? At first, I thought `useCallback` will be rare, just when we need special performances. In this cases, codebases will be full of `useCallback` everywhere.

The `useRedux` hook we propose is way more simple, look a lot like the good old `connect` and we discovered in usage that the memoization argument is often the same for state and dispatch.

**Comment by FBerthelot** [comment]
I know this "shortcut" seem a little bit big for a tiny library. But It actually make it reduce a lot the applications code and make refactoring to hook way more easy.

Let's take an exemple of a Like Button. The code below is without hooks:

like-button.container.js
```jsx
import {connect} from 'react-redux';
import LikeButton from './like-button';

const mapStateToProps = (state, props) => ({
     nbOfLike: state.likes[props.index],
     nbOfFav: state.favs[props.index],
     likeIndex: props.index
     // Assuming more state extration here for a bigger component
})

const mapDispatchToProps = dispatch => ({
   handleLike: () => index => dispatch({
      type: 'LIKE BUTTON',
      payload: {index}
   }),
    handleFav: () => index => dispatch({
      type: 'FAV BUTTON',
      payload: {index}
   })
})

export default connect(mapStateToProps, mapDispatchToProps)(LikeButton);
```

like-button.js
``` jsx
const LikeButton = ({nbOfLike, handleLike, likeIndex}) => {
  return <button onClick={handleLike(likeIndex)}>{nbOfLike}</button>;
}
export default LikeButton;
```

Assuming using the library right now the code will merge into one component and will look like this :

like-button.js
```jsx
const LikeButton = ({index}) => {
  const dispatch = useDispatch();
  const handleLike = useCallback(
    () =>
      dispatch({
      type: 'LIKE BUTTON',
      payload: {index}
   }),
    [index],
  );

const handleFav = useCallback(
    () =>
      dispatch({
      type: 'FAV BUTTON',
      payload: {index}
   }),
    [index],
  );
   
  const mapState = useCallback(state => ({
    nbOfLike: state.likes[index],
    nbOfFav: state.favs[index],
 }, [index]);
  const {nbOfLike, handleFav}  = useMappedState(mapState);

  return (<>
     <button onClick={handleLike}>{nbOfLike} :+1:</button>
     <button onClick={handleFav}>{nbOfFav} <3</button>
   </>);
}
export default LikeButton;
```

Imagine refactoring from the first example to the second is really painful, it's a bit too far from the connect function. The code which generate function that dispatch actions is also not really clear to me. It's a little bit messy as the number of these function grow. Our proposal it to be as close as possible to the old connect function.

```jsx
const LikeButton = ({index}) => {
  const mapDispatch = dispatch =>  ({
   handleLike: () => index => dispatch({
      type: 'LIKE BUTTON',
      payload: {index}
   }),
    handleFav: () => index => dispatch({
      type: 'FAV BUTTON',
      payload: {index}
   })
});
  const mapState = state => ({
    nbOfLike: state.likes[index],
    nbOfFav: state.favs[index],
 });
  const {nbOfLike, handleFav}  = useRedux(mapState, mapDispatch, [index]);

  return (<>
     <button onClick={handleLike}>{nbOfLike} :+1:</button>
     <button onClick={handleFav}>{nbOfFav} <3</button>
   </>);
}
export default LikeButton;
```

As you may see, refactoring from step one to final is way simpler, function `mapStateToProps` is renamed `mapState` and can directly access to props. It's way simpler. It's same for `mapDispatchToProps` function.

Hope you will find my example usefull :slightly_smiling_face:

Maybe you've some other idea to make the API more similaire to `connect` ?

**Comment by ianobermiller** [comment]
> refactoring from step one to final is way simpler

While facilitating refactoring from `react-redux` is nice, it really isn't a goal of `redux-react-hook`. If we have `useMappedDispatch` and `useMappedState` that take a dependency array, both the hook versions are larger than vanilla `connect`, but of course they have all the benefits of hooks (defined inline, vastly easier to type with TS or Flow, composable, etc). Trying to make them like-for-like, I really don't see the advantage of combining everything into a single `useRedux` call:

`connect`: 28 lines:
```tsx
const LikeButton = ({nbOfFav, nbOfLike, handleLike, likeIndex}) => {
  return (
    <>
      <button onClick={handleLike}>{nbOfLike} :+1:</button>
      <button onClick={handleFav}>{nbOfFav} fav</button>
    </>
  );
};

const mapStateToProps = (state, props) => ({
  nbOfLike: state.likes[props.index],
  nbOfFav: state.favs[props.index],
});

const mapDispatchToProps = dispatch => ({
  handleLike: () => index =>
    dispatch({
      type: 'LIKE BUTTON',
      payload: {index},
    }),
  handleFav: () => index =>
    dispatch({
      type: 'FAV BUTTON',
      payload: {index},
    }),
});

export default connect(mapStateToProps, mapDispatchToProps)(LikeButton);
```

`useRedux`: 30 lines
```tsx
export default function LikeButton({index}) {
  const {nbOfLike, nbOfFav, handleLike, handleFav} = useRedux(
    state => ({
      nbOfLike: state.likes[index],
      nbOfFav: state.favs[index],
    }),
    dispatch => ({
      handleLike(index) {
        dispatch({
          type: 'LIKE BUTTON',
          payload: {index},
        });
      },
      handleFav(index) {
        dispatch({
          type: 'FAV BUTTON',
          payload: {index},
        });
      },
    }),
    [index],
  );

  return (
    <>
      <button onClick={handleLike}>{nbOfLike} :+1:</button>
      <button onClick={handleFav}>{nbOfFav} fav</button>
    </>
  );
};
```

`useMappedState` and `useMappedDispatch`: 33 lines

```tsx
export default function LikeButton({index}) {
  const {nbOfLike, nbOfFav} = useMappedState(
    state => ({
      nbOfLike: state.likes[index],
      nbOfFav: state.favs[index],
    }),
    [index],
  );
  const {handleLike, handleFav} = useMappedDispatch(
    dispatch => ({
      handleLike(index) {
        dispatch({
          type: 'LIKE BUTTON',
          payload: {index},
        });
      },
      handleFav(index) {
        dispatch({
          type: 'FAV BUTTON',
          payload: {index},
        });
      },
    }),
    [index],
  );

  return (
    <>
      <button onClick={handleLike}>{nbOfLike} :+1:</button>
      <button onClick={handleFav}>{nbOfFav} fav</button>
    </>
  );
}
```

**Comment by Swiip** [comment]
I think that what bother me most is to handle memoization explicitly with `useCallback`. I thinks it's too heavy for an everyday use.
Binding `mapState` and `dispatch` in a single `useRedux` in a single hook is much less important. I agree that it's possible that's a bad idea.
I think that your proposition with `useMappedState` and `useMappedDispatch` that take a dependency array is really neat.

**Comment by FBerthelot** [comment]
First, I want to thank you a lot for tooking time to answer us :)

Your last solution is looking great too and answer our main issue of heavy use of useCallback.

If you want help for implementing `useMappedDispatch` just ask. I want help ;)

**Pull request closed without merging**
