### PR TITLE
Add create function

### PR DESCRIPTION
**Pull request by nmn**
To pass in a static store and get pre-typed versions of the hooks. Ideally, this function would create a fresh Context value with the store value pre-set so that the type doesn't have to accept null at all.

### CODE REVIEW

**Comment by nmn** [comment]
Will update to fix types.

**Comment by ianobermiller** [comment]
What do you think about `create()` instead?

**Comment by nmn** [comment]
@ianobermiller Looks like you fixed my diff! looks good to me.

Didn't think about passing type args without actual args to `create`.

**Comment by ianobermiller** [comment]
@nmn this should work fine with Flow as well. In fact, we might want to either add some flow types directly in this package or add them to flow-typed.

**Comment by nmn** [comment]
I can add flow types for this no problem. I can make a PR to flow-typed but I’m not sure what the best practice is on how to add into lib itself anymore.

**Comment by ianobermiller** [comment]
> I’m not sure what the best practice is on how to add into lib itself anymore

I don't know if there is such a practice. flow typed is fine. Also sorry that I messed up your PR repo with the merge commit, I am not very good with git :)

**Comment by ianobermiller** [comment]
Closed by d68d7a1df3fb1e00c96ba3a8d9cd3ebb557184aa

**Pull request closed without merging**
